# Generated by Django 2.2.1 on 2020-03-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0005_auto_20200328_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
